main_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage_view, name="home"),
    path('reports', views.data_analysis, name="reports"),
    path('accounts/', include("accounts.urls")),
    path('users/', include('users.urls')),
    path('ppty/', include('properties.urls')),
    path('paymts/', include('payments.urls')),
    path('maintain/', include('maintain.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('ownreg', views.register_owner_view, name="registerOwners"),
    path('tenreg', views.register_tenant_view, name="registerTenant"),
    path('buyreg', views.buyer_registration_view, name="registerBuyer"),
    path('ajax/load-properties/', views.load_cities, name='ajax_load_properties'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('tenant/<tenant_id>', views.tenant_detail_view, name="tenant_detail"),
    path('<tenant_id>/delete/', views.remove_tenant_view, name="remove_tenant"),
    path('send/<id>', views.message_view, name="message"),
    path('maintain/<id>', views.maintainers_view, name="maintainer_info"),
    path('remove/maintainer/<id>', views.remove_maintainer_view,
         name="remove_maintainer"),
    path('remove/rent_ppty/<id>', views.remove_rent_listing_view,
         name="remove_rental_property"),
    path('remove/sale_ppty/<id>', views.remove_sale_listing_view,
         name="remove_sale_property"),
    # path('rentreg', views.register_property_rent_view, name="rentalRegistration")
]

users/models.py
from payments.models import RentPayment
import datetime
from properties.models import PropertyForRent
from accounts.models import Account
from django.db import models
from django.conf import settings
User = settings.AUTH_USER_MODEL
# Create your models here.


class Owners(models.Model):
    owner = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    acc_no = models.CharField(max_length=16)

    def __str__(self):
        return self.owner.username

    class Meta:
        verbose_name = "Owner"
        verbose_name_plural = "Owners"


class Tenant(models.Model):
    property_owner = models.ForeignKey(
        Account, default=None, related_name="owner_name", on_delete=models.CASCADE)
    tenant = models.ForeignKey(
        User,  default=None, on_delete=models.CASCADE)
    property = models.ForeignKey(
        PropertyForRent, default=None, on_delete=models.CASCADE)
    aadhar_no = models.CharField(max_length=12)
    acc_no = models.CharField(max_length=16)
    ifsc_code = models.CharField(max_length=11, default='xxxxxxxxxxx')
    address_proof = models.ImageField(
        default='address_proofs/default.jpg', upload_to='address_proofs/')
    start_date = models.DateTimeField(
        auto_now_add=True)

    def __str__(self):
        return self.property.property_name + " - " + self.property.floor_no + ' - ' + self.tenant.username

    class Meta:
        verbose_name = "Tenant"
        verbose_name_plural = "Tenants"


class Buyers(models.Model):
    CHOICES = (
        ('Agent', "Agent"),
        ('Buyer', 'Buyer'),
    )
    name = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    catagory = models.CharField(
        max_length=20, choices=CHOICES, default="Buyer")

    def __str__(self):
        return self.name.username + " - " + self.catagory

    class Meta:
        verbose_name = "Buyer"
        verbose_name_plural = "Buyers"

users/forms.py
from users.models import Account
from . models import Owners, Tenant, Buyers
from properties.models import PropertyForRent
from django import forms
from django.conf import settings
User = settings.AUTH_USER_MODEL


class RegisterOwners(forms.ModelForm):
    class Meta:
        model = Owners
        fields = [
            'acc_no',
        ]


class TenantRegistrationForm(forms.ModelForm):

    class Meta:
        model = Tenant
        fields = [
            'property_owner',
            'property',
            'aadhar_no',
            'acc_no',
            'address_proof',
            'ifsc_code',
        ]

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        self.fields['property'].queryset = PropertyForRent.objects.all()
        accounts = Account.objects.filter(
            is_ppty_owner=True).exclude(id=self.user.id)
        self.fields['property_owner'].queryset = accounts


class BuyerRegistrationForm(forms.ModelForm):
    class Meta:
        model = Buyers
        fields = ['catagory', ]

users/views.py
from django.db import connection
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from accounts.models import Account
from . forms import RegisterOwners, TenantRegistrationForm, BuyerRegistrationForm
from properties.models import PropertyForRent, PropertyForSale, Appointment, visit
from django.shortcuts import render, redirect
from . models import Tenant
import datetime
# import pywhatkit
from payments.models import RentPayment
from django.conf import settings
User = settings.AUTH_USER_MODEL


def register_owner_view(request):
    account = Account.objects.get(id=request.user.id)
    if request.method == "POST":
        form = RegisterOwners(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.owner = request.user
            account.is_ppty_owner = True
            account.save()
            instance.save()
            return redirect('home')
    else:
        form = RegisterOwners()
    return render(request, 'users/register_user.html', {'register_owner_form': form})


def register_tenant_view(request):
    account = Account.objects.get(id=request.user.id)
    properties = PropertyForRent.objects.all()
    if request.POST:
        form = TenantRegistrationForm(request.POST, user=request.user)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.tenant = request.user
            account.is_tenant = True
            pid = instance.property.id
            property = properties.get(id=pid)
            property.is_occupied = True
            property.save()
            account.save()
            instance.save()
            return redirect('home')
    else:
        form = TenantRegistrationForm(user=request.user)
    return render(request, 'users/register_tenant.html', {'tenant_reg_form': form, })


def tenant_detail_view(request, tenant_id):
    tenant = Tenant.objects.get(id=tenant_id)
    context = {
        'tenant': tenant,
    }
    return render(request, 'users/tenant_detail.html', context)


def remove_tenant_view(request, tenant_id):
    item = Tenant.objects.get(id=tenant_id)
    user = Account.objects.get(id=item.tenant.id)
    ppty = PropertyForRent.objects.get(id=item.property.id)
    if request.POST:
        user.is_tenant = False
        ppty.is_occupied = False
        ppty.save()
        user.save()
        item.delete()
        return redirect('dashboard')
    context = {
        "item": item,
    }
    return render(request, 'users/remove_tenant.html', context)


def load_cities(request):
    owner_id = request.GET.get('owner_id')
    properties = PropertyForRent.objects.filter(owner_id=owner_id)
    properties = properties.filter(is_occupied=False)
    return render(request, 'users/property_dropdown_list_options.html', {'properties': properties})
    # return JsonResponse(list(cities.values('id', 'name')), safe=False)


@login_required(login_url="/accounts/login/")
def dashboard_view(request):
    context = {}
    tenants = Tenant.objects.filter(property_owner=request.user)
    visits = visit.objects.all().filter(
        owner=request.user).order_by('date_appointement')
    visits = visits.filter(date_appointement__gte=datetime.date.today())
    context['visit'] = visits
    try:
        rental_house = Tenant.objects.get(tenant=request.user)
        payment_status = RentPayment.objects.filter(
            month_of=datetime.date.today().month)
        print(payment_status)
        payment_status = payment_status.get(sender=request.user)
        if payment_status.rent_paid == True:
            context['rent_status'] = True
    except Tenant.DoesNotExist:
        rental_house = None
        # context['rent_status'] = False
    except RentPayment.DoesNotExist:
        context['rent_status'] = False
    properties = PropertyForRent.objects.filter(owner=request.user)

    unoccupied_houses = properties.filter(is_occupied=False)
    print(unoccupied_houses, properties)
    appointments = Appointment.objects.all().filter(
        owner=request.user).order_by('date_appointement')
    appointments = appointments.filter(
        date_appointement__gte=datetime.date.today())
    context['appointments'] = appointments
    rents_done = 0
    rents_left = 0
    occupied_houses = PropertyForRent.objects.filter(
        owner=request.user).filter(is_occupied=True)
    rents_current_owner = RentPayment.objects.filter(
        reciever=request.user).filter(month_of=datetime.date.today().month)
    rents_done = rents_current_owner.count()
    rents_left = occupied_houses.count() - rents_done
    context['rents_done'] = rents_done
    context['rents_left'] = rents_left
    context['rents'] = rents_current_owner
    no_properties_total = properties.count()
    no_properties_occupied = occupied_houses.count()
    no_properties_unoccupied = unoccupied_houses.count()
    total_rent = 0
    total_deposit = 0
    average_rent = 0
    for x in occupied_houses:
        total_rent += x.rent
        total_deposit += x.security_deposit
    try:
        average_rent = total_rent/no_properties_occupied
    except:
        average_rent = 0
    context['average_rent'] = average_rent
    context['total_deposit'] = total_deposit
    context['no_properties_unoccupied'] = no_properties_unoccupied
    context['no_properties_occupied'] = no_properties_occupied
    context['total_properties_rent'] = no_properties_total
    context['rental_house'] = rental_house
    context['tenants'] = tenants
    context['unoccupied_houses'] = unoccupied_houses
    context['total_rent'] = total_rent
    sale_houses = PropertyForSale.objects.filter(owner=request.user)
    context['houses'] = sale_houses
    # print(datetime.date.today())
    return render(request, 'users/dashboard.html', context)


def buyer_registration_view(request):
    context = {

    }
    if request.POST:
        form = BuyerRegistrationForm(request.POST)
        account = Account.objects.get(username=request.user.username)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.name = request.user
            account.is_buyer = True
            account.save()
            instance.save()
            return redirect('dashboard')
    else:
        form = BuyerRegistrationForm()
    context['buyer_registration_form'] = form
    return render(request, 'users/register_buyer.html', context)


def message_view(request, id):
    # if request.POST:
    #     sender = request.user.ph_no
    #     reciever = Account.objects.all().get(id=id).ph_no
    #     reciever = "+91"+reciever
    #     message = request.POST.get('message_id')

    # try:
    #     current_hour = int(datetime.datetime.now().hour)
    #     current_minute = int(datetime.datetime.now().minute + 2)
    #     try:
    #         pywhatkit.sendwhatmsg(reciever,
    #                               message,
    #                               current_hour, current_minute)
    #         print(sender, reciever, message)
    #         return redirect('dashboard')
    #     except:
    #         print("No whatsApp messaging functionality due to lack of wifi networks")
    # except:
    #     print("unexpected error has occured")
    return render(request, 'users/message.html')


def maintainers_view(request, id):
    cursor = connection.cursor()
    context = {}
    cursor.execute(
        'select m_id, name, ph_no from maintainers_rent where p_id = %s', [id])
    property = PropertyForRent.objects.get(id=id)
    information = cursor.fetchall()

    context['id'] = information[0][0]
    context['name'] = information[0][1]
    context['ph_no'] = information[0][2]
    context['property'] = property
    cursor.close()
    return render(request, 'users/maintainer_info.html', context)


def remove_maintainer_view(request, id):
    if request.POST:
        cursor = connection.cursor()
        cursor.execute(
            'select p_id from maintainers_rent where m_id = %s', [id])
        p_id = cursor.fetchall()
        p_id = p_id[0][0]
        cursor.execute('delete from maintainers_rent where m_id = %s', [id])
        property = PropertyForRent.objects.get(id=p_id)
        property.has_maintainer = False
        property.save()
        cursor.close()
        return redirect('dashboard')


def remove_rent_listing_view(request, id):
    if request.POST:
        property = PropertyForRent.objects.get(id=id)
        property.delete()

        return redirect('dashboard')


def remove_sale_listing_view(request, id):
    if request.POST:
        property = PropertyForSale.objects.get(id=id)
        property.delete()

        return redirect('dashboard')

users/templates/users/dashboard.html
{% extends 'base.html' %}

{% block content %}
<style>
    /* .details {
        margin: auto;
        background: #f2f2f2;
        padding: 3rem;
        border-radius: 12px;
        box-shadow: 12px 13px 15px rgba(127, 137, 161, 0.25);
        ;
    }

    .details:hover {
        box-shadow: 8px 7px 15px rgba(127, 137, 161, 0.25);
    } */
</style>

<!-- /.container -->
<div class="container">
    <ul class="nav nav-tabs">
        <li class="nav-item" id="users" onclick="user_show()">
            <a class="nav-link " href="#">User Details</a>
        </li>
        <li class="nav-item" id="rent" onclick="rental_show()">
            <a class="nav-link " href="#">Rentals</a>
        </li>
        <li class="nav-item" id="sale" onclick="sale_show()">
            <a class="nav-link" href="#">Sale</a>
        </li>
        <li class="nav-item" id="payment" onclick="pay_show()">
            <a class="nav-link" href="#">Payments</a>
        </li>
        <li class="nav-item" id="app" onclick="app_show()">
            <a class="nav-link " href="#">Appointments</a>
        </li>
    </ul>

    <div id='user' style="padding:3rem;background-color: #f2f2f2;">
        <div class="details">
            <h1>User details</h1>
            <p>Name: {{request.user.username}}</p>
            <p>Address: {{request.user.address}}</p>
            <p>Phone Number: {{request.user.ph_no}}</p>
            <p>Is a property owner: {% if request.user.is_ppty_owner %}Yes {% else %} No {% endif %}</p>
            <p>Is a Tenant: {% if request.user.is_tenant %}yes {% else %} No {% endif %}</p>

        </div>

    </div>

    <div id="rental-section" style="display:none; background: #f2f2f2;padding:3rem;">
        {% if rental_house %}
        <div class="details">
            <h1>Your rental house </h1>
            {{ rental_house.property }}
            {% if rent_status %}
            <p>Rent paid </p>
            {% else %}
            <a href="{% url 'payment_rent' %}">Pay rent for the month</a>
            {% endif %}
            <hr style="background-color: black;">
        </div>
        {% else %}
        <p>You aren't a tenant. Register as a tenant here</p>
        {% endif %}

        {% if unoccupied_houses %}
        <h1>All your properties for rent (Unoccupied)</h1>
        {% for property in unoccupied_houses %}
        {{property.property_name}}
        <br>


        <a href="{% url 'property_rent_detail' property.id %}">more info</a>
        <br>
        <a href="#" data-toggle="modal" data-target="#myModal{{property.id}}rent">Remove Listing in the page</a>
        <br>
        {% if property.has_maintainer %}
        <a href="{% url 'maintainer_info' property.id %}">maintainer information</a>
        {% else %}
        <a href="{% url 'maintainers' property.id %}">Add a maintainance personal</a>
        {% endif %}
        <!-- modal for removing the property from listing  -->
        <div class="modal fade" id="myModal{{property.id}}rent" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">

                        <h4 class="modal-title">Property information</h4>
                    </div>
                    <div class="modal-body">
                        are you sure you want to remove <span
                            style="color:yellow; background:red;">{{property.property_name}}</span>
                        <form action="{% url 'remove_rental_property'  property.id %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Confirm removal of listing</button>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>

            </div>
        </div>

        <br>
        <hr>
        {% endfor %}
        {% else %}
        <p>You don't have any houses registered for rent. Register here.</p>
        {% endif %}

        {% if tenants %}
        <h1>Tenants that are staying in your property</h1>
        {% for tenant in tenants %}
        {{tenant.tenant}}
        <br>
        {{tenant.start_date}}
        <br>
        {{tenant.property.rent}}
        <br>
        <a href="{% url 'remove_tenant' tenant.id %}">Remove Tenant</a><br>
        <a href="{% url 'tenant_detail' tenant.id %}">More information</a><br>
        <form action="{% url 'message' tenant.id %}" method="GET">
            {% csrf_token %}
            <button type="submit">Message on WhatsApp</button>
        </form>



        <hr style="background-color: black;">

        {% endfor %}
        {% endif %}
    </div>
    <div id="sale-section" style="display:none ; background: #f2f2f2;padding:3rem;">

        {% if houses %}
        <h1>Properties registered for sale</h1>
        {% for house in houses %}
        <p>{{house.address}}</p>

        <a href="#" type="button" class="" data-toggle="modal" data-target="#myModal{{house.id}}">More information</a>
        <br>
        <a href="#" data-toggle="modal" data-target="#myModal{{house.id}}sale">Remove Listing in the page</a>
        <hr>
        <div class="modal fade" id="myModal{{house.id}}" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">

                        <h4 class="modal-title">Property information</h4>
                    </div>
                    <div class="modal-body">
                        <p>Full Address: {{house.address}}</p>
                        <p>Dimensions: {{house.width}}*{{house.length}}</p>
                        <p>Cost per Sqft: {{house.cost_sqft}}</p>
                        <p>Ceritification: {{house.ceritification}}-Khata</p>
                        <p>Description: {{house.description | linebreaks }}</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>

            </div>
        </div>
        <!-- modal for removing sale property  -->
        <div class="modal fade" id="myModal{{house.id}}sale" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">

                        <h4 class="modal-title">Property information</h4>
                    </div>
                    <div class="modal-body">
                        are you sure you want to remove <span
                            style="color:yellow; background:red;">{{house.address}}</span>??
                        <form action="{% url 'remove_sale_property'  house.id %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Confirm removal of listing</button>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>

            </div>
        </div>
        {% endfor %}
        {% else %}
        <p>You don't have any properties registered for sale. Register here.</p>
        {% endif %}
    </div>
    <div id="Payments" style="display:none ; background: #f2f2f2;padding:3rem;">
        <h1>Rent Payments detail</h1>
        {% if rents %}
        {% for rent in rents %}
        <p>Name - {{rent.sender}} </p>
        <p>transaction_id - {{rent.transaction_id}}</p>
        <p>month of - {{rent.month_of}}</p>
        <p>Status - successful</p>
        <hr>
        {% endfor %}
        {% else %}
        <p>No transactions made for this month.</p>
        {% endif %}
    </div>
    <div id="Appointments" style="display:none ; background: #f2f2f2;padding:3rem;">
        <h1>Appointments coming up for sale </h1>
        {% if appointments %}
        {% for appointment in appointments %}
        <p>Visitor Username: {{appointment.user}}</p>
        <p>Property: {{appointment.property}}</p>
        <p>Time: {{appointment.time_appointment}}</p>
        <p>Date: {{appointment.date_appointement}}</p>
        <hr>
        {% endfor %}
        {% else %}
        <p>No Visits for your property for sale</p>
        {% endif %}
        <h1>Upcoming visits to your rental properties</h1>
        {% if visit %}

        {% for vis in visit %}

        <p>Visitor Username: {{vis.visitor}}</p>
        <p>Property: {{vis.property}}</p>
        <p>Time: {{vis.time_appointment}}</p>
        <p>Date: {{vis.date_appointement}}</p>
        <hr>
        {% endfor %}
        {% else %}
        <p>No Visits for your property for rent</p>
        {% endif %}
    </div>

</div>

<script>
    let rent = document.getElementById('rental-section');
    let sales = document.getElementById('sale-section');
    let payments = document.getElementById('Payments');
    let app = document.getElementById('Appointments');
    let user = document.getElementById('user');


    function user_show() {
        user.style.display = "block";
        rent.style.display = "none";
        sales.style.display = "none";
        payments.style.display = "none";
        app.style.display = "none";
    }


    function rental_show() {
        rent.style.display = "block";
        sales.style.display = "none";
        payments.style.display = "none";
        app.style.display = "none";
        user.style.display = "none";
    }
    function sale_show() {
        rent.style.display = "none";
        sales.style.display = "block";
        payments.style.display = "none";
        app.style.display = "none";
        user.style.display = "none";
    } function app_show() {
        rent.style.display = "none";
        sales.style.display = "none";
        payments.style.display = "none";
        app.style.display = "block";
        user.style.display = "none";
    } function pay_show() {
        rent.style.display = "none";
        sales.style.display = "none";
        payments.style.display = "block";
        app.style.display = "none";
        user.style.display = "none";
    }

</script>

<!-- <h1>user details</h1>
<p>{{request.user.username}}</p>
{% if request.user.is_ppty_owner %}
<p>Total number of houses for rent : {{total_properties_rent}}</p>
<p>Number of houses currently occupied: {{no_properties_occupied}}</p>
<p>Number of properties remaining to be occupied: {{no_properties_unoccupied}}</p>
<p>total security deposit in hand: {{total_deposit}} </p>
<p>total rent monthy: {{total_rent}} </p>
<p>Rents left: {{rents_left}}</p>
<p>Rents paid: {{rents_done}}</p>
<p>average rent per house: {{average_rent}} </p>
{% endif %}
<p>number of properties for sale: </p>
<hr style="background-color: black;"> -->
<!-- unoccupied houses for rent -->
<!-- {% if unoccupied_houses %}
<h1>All your properties for rent </h1>
{% for property in unoccupied_houses %}
{{property.property_name}}
<br>
<a href="{% url 'property_rent_detail' property.id %}">more info</a>
<br>
<hr style="background-color: black;">
{% endfor %}
{% endif %} -->
<!-- if the user stays in rented place -->
<!-- {% if rental_house %}
<h1>Your rental house </h1>
{{ rental_house.property }}
{% if rent_status %}
<p>Rent paid </p>
{% else %}
<a href="{% url 'payment_rent' %}">Pay rent for the month</a>
{% endif %}
<hr style="background-color: black;">
{% endif %} -->
<!-- if the user has tenants occupying his property -->
<!-- {% if tenants %}
<h1>Tenants that are staying in your property</h1>
{% for tenant in tenants %}
{{tenant.tenant}}
<br>
{{tenant.start_date}}
<br>
{{tenant.property.rent}}

<br>
<a href="{% url 'remove_tenant' tenant.id %}">Remove Tenant</a><br>
<a href="{% url 'tenant_detail' tenant.id %}">More information</a><br>

<hr style="background-color: black;">

{% endfor %}
<h1>Rent information detail</h1>
{% for rent in rents %}
<p>Name - {{rent.sender}} </p>
<p>transaction_id - {{rent.transaction_id}}</p>
<p>month of - {{rent.month_of}}</p>
<p>Status - successful</p>

{% endfor %}
{% endif %}
<hr>
<h1>Properties registered for sale</h1>
{% if houses %}
{% for house in houses %}
<p>{{house.no}}</p>
<p>{{house.locality}}</p>
<p>{{house.area}}</p>
<p>{{house.state}}</p>
<p>{{house.width}}*{{house.length}}</p>
<p>{{house.cost_sqft}}</p>
<p>{{house.ceritification}}-Khata</p>
<hr>


{% endfor %}
{% endif %}
{% if appointments %}
<h1>Appointments coming up</h1>
{% for appointment in appointments %}
{{appointment.date_appointement}}
{% endfor %}
{% endif %}

{% if visit %}
<h1>Upcoming visits to your rental properties</h1>
{% for vis in visit %}
{{vis.property}}
{{vis.visitor}}
{{vis.date_appointement}}
{{vis.time_appointment}}
{% endfor %}
{% endif %} -->

{% endblock %}

users/templates/users/maintainer_info.html
{% extends 'base.html' %}
{% block content %}
<h2>Maintainer information</h2>
<p>{{name}}</p>
<p>{{ph_no}}</p>
<p>
    {{property}}
</p>
<a href="#" data-toggle="modal" data-target="#myModal{{id}}">Remove Maintainer</a>
<!-- <div class="modal fade" id="myModal{{name}}" role="dialog">
    <div class="modal-dialog">

        
        <div class="modal-content">
            <div class="modal-header">

                <h4 class="modal-title">Property information</h4>
            </div>
            <div class="modal-body">
                <form action="{% url 'remove_maintainer' id %}" method="POST">
                    {% csrf_token %}
                    <p>Do you want to remove {{name}} as maintainer from {{property}}??</p>
                    <button type="submit" class="btn btn-danger">Confirm</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div> -->
<div class="modal fade" id="myModal{{id}}" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">

                <h4 class="modal-title">Property information</h4>
            </div>
            <div class="modal-body">
                <div class="modal-body">
                    <form action="{% url 'remove_maintainer' id %}" method="POST">
                        {% csrf_token %}
                        <p>Do you want to remove {{name}} as maintainer from {{property}}??</p>
                        <button type="submit" class="btn btn-danger">Confirm</button>
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>
{% endblock %}

users/templates/users/message.html
{% extends 'base.html' %}
{% block content %}
<style>

</style>
<h1>Send a message on WhatsApp</h1>

<form method="POST" class="text-center border border-light p-5" style="margin:10px;">
    {% csrf_token %}
    <label for="message_id" class="form-control">Enter your message</label>
    <br>
    <textarea rows="5" cols="60" id="message_id" name="message_id" class="form-control"></textarea>
    <button type="submit" class="btn btn-primary" style="margin-top:15px;">Send Message</button>
</form>


{% endblock %}

users/templates/users/property_dropdown_list_options.html
<option value="">---------</option>
{% for property in properties %}
<option value="{{ property.pk }}">{{ property.property_name }}</option>
{% endfor %}

users/templates/users/register_buyer.html
{% extends 'base.html' %}
{%load crispy_forms_tags %}
{% block content %}
<div class="section-title">
    <h2>Register as a buyer of properties</h2>
</div>
<form action="{% url 'registerBuyer' %}" method="POST" class="text-center border border-light p-5">
    {% csrf_token %}
    {{buyer_registration_form|crispy}}
    <button type="submit" class="btn btn-primary">Register as buyer</button>
</form>
{% endblock %}

users/templates/users/register_tenant.html
{% extends 'base.html' %}
{%load crispy_forms_tags %}
{% block content %}


<h2>Register</h2>
<form method="post" id="property_form" action="{% url 'registerTenant' %}"
    data-properties-url="{% url 'ajax_load_properties' %}" class="text-center border border-light p-5">{% csrf_token %}
    <!-- {% for field in tenant_reg_form %}
    <p>
        {{field.label_tag}}
        {{field}}

        {% if field.help_text %}
        <small style="color: grey;">{{field.help_text}}</small>
        {% endif %}

        {% for error in field.errors %}
    <p style="color: red;">{{error}}</p>
    {% endfor %}
    </p>
    {% endfor %} -->
    {{tenant_reg_form|crispy}}
    <button type="submit" class="btn btn-primary">Register as tenant</button>

</form>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_property_owner").change(function () {
        const url = $("#property_form").attr("data-properties-url");
        const ownerId = $(this).val();

        $.ajax({
            url: url,
            data: {
                'owner_id': ownerId
            },
            success: function (data) {
                $("#id_property").html(data);
            }
        });

    });
</script>
{% endblock %}

users/templates/users/register_user.html
{% extends 'base.html' %}
{%load crispy_forms_tags %}
{% block content %}

<form action="{% url 'registerOwners'  %}" method="POST" class="text-center border border-light p-5">
    <h2>Regsiter as a Property owner</h2>
    {% csrf_token %}
    {{register_owner_form|crispy}}

    <button type="submit" class="btn btn-primary">submit</button>

</form>
{% endblock %}